version: "3.7"
services:
  web:
    container_name: orderAppService
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      HOST: db
      PORT: 1500
      USER_NAME: root
      PASSWORD: root
      DATABASE: order
      PAYMENT_HOST: http://127.0.0.1:3000/api/v1/payment

  # Database
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      DATABASE: order
      USER_NAME: root
      PASSWORD: root

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root